//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> MatchPlayed { get; set; }
        public string Contact { get; set; }
        public string EmailId { get; set; }
        public System.DateTime DOB { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public string Status { get; set; }
    }
}
